# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes tilde M_i
#'
#' @param S_star Field of Matrices containing basis functions evaluated at unobserved time points
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param i Int indicating which M we are calculating
#' @param Z_plus Matrix acting as a placeholder for Z_plus.
#' @param M Matrix acting as a placeholder for M
NULL

#' Computes all tilde M
#'
#' @param S_star Field of Matrices containing basis functions evaluated at unobserved time points
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param i Int indicating which M we are calculating
#' @param Z_plus Field of Matrices acting as a placeholder for Z_plus.
#' @param tilde_M Field of Matrices acting as a placeholder for M
NULL

#' Computes tilde m_i
#'
#' @param S_star Field of Matrices containing basis functions evaluated at unobserved time points
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param f_obs vector of current f values at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param nu Matrix of current nu paramaters
#' @param i Int indicating which tilde_m we are calculating
#' @param Z_plus Matrix acting as a placeholder for Z_plus
#' @param A_plus Matrix acting as a placeholder for A_plus
#' @param C Matrix acting as a placeholder for C
#' @param tilde_m vector acting as a placeholder for tilde_m
NULL

#' Computes all tilde m
#'
#' @param S_star Field of Matrices containing basis functions evaluated at unobserved time points
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param f_obs vector of current f values at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param nu Matrix of current nu paramaters
#' @param Z_plus Matrix acting as a placeholder for Z_plus
#' @param A_plus Matrix acting as a placeholder for A_plus
#' @param C Matrix acting as a placeholder for C
#' @param tilde_m matrix acting as a placeholder for tilde_m
NULL

#' Computes M_i
#'
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param i Int indicating which M we are calculating
#' @param M Matrix acting as a placeholder for M
#' @export
computeMi <- function(S_obs, Z, phi, i, M) {
    invisible(.Call('_BayesFOC_computeMi', PACKAGE = 'BayesFOC', S_obs, Z, phi, i, M))
}

#' Computes all M matrices
#'
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param M Cube containing all M matrices
#' @export
computeM <- function(S_obs, Z, phi, M) {
    invisible(.Call('_BayesFOC_computeM', PACKAGE = 'BayesFOC', S_obs, Z, phi, M))
}

#' Computes m_i
#'
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param nu Matrix of current nu parameters
#' @param i Int indicating which M we are calculating
#' @param m vector acting as a placeholder for m
#' @export
compute_mi <- function(S_obs, Z, phi, nu, i, m) {
    invisible(.Call('_BayesFOC_compute_mi', PACKAGE = 'BayesFOC', S_obs, Z, phi, nu, i, m))
}

#' Computes all m vectors
#'
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param Z Matrix of current Z parameter
#' @param phi Cube of current phi paramaters
#' @param nu Matrix of current nu parameters
#' @param m matrix acting as a placeholder for m
#' @export
compute_m <- function(S_obs, Z, phi, nu, m) {
    invisible(.Call('_BayesFOC_compute_m', PACKAGE = 'BayesFOC', S_obs, Z, phi, nu, m))
}

#' Updates the parameters pi_1 through pi_K
#'
#' @param Z Binary matrix of containing inclusion/exclusion to the various groups
#' @param alpha Hyperparameter for distribution of pi_i
#' @param K Number of clusters
#' @param iter Iteration of MCMC step
#' @param pi Matrix conatining all past, current, and future MCMC draws
#' @export
updatePi <- function(Z, alpha, K, iter, pi) {
    invisible(.Call('_BayesFOC_updatePi', PACKAGE = 'BayesFOC', Z, alpha, K, iter, pi))
}

#' Gets generalized log determinant (product of positive eigen values)
#'
#' @param M Matrix that we want the determinant of
#' @return g_ldet Double countaining the generalized determinant
#' @export
g_ldet <- function(M) {
    .Call('_BayesFOC_g_ldet', PACKAGE = 'BayesFOC', M)
}

#' Gets log-pdf of z given zeta
#'
#' @param M Cube that contains the M_i variance matrices
#' @param m Matrix that contains the m_i mean vectors
#' @param tilde_M Cube that contains the tilde_M_i variance matrices
#' @param tilde_m Matrix that contains the tilde_M_i mean vectors
#' @param f_obs Vector containing f at observed time points
#' @param f_star Vector containing f at unobserved time points
#' @param pi Vector containing the sampled pi for this iteration
#' @return lpdf_z Double contianing the log-pdf
#' @export
lpdf_z <- function(M, m, tilde_M, tilde_m, f_obs, f_star, pi_l, z_il, pinv_M, pinv_tilde_M) {
    .Call('_BayesFOC_lpdf_z', PACKAGE = 'BayesFOC', M, m, tilde_M, tilde_m, f_obs, f_star, pi_l, z_il, pinv_M, pinv_tilde_M)
}

#' Updates the ith row of the Z Matrix
#'
#' @param M Cube that contains all M matrices
#' @param M_ph Matrix that acts as a placeholder for the new M matrix
#' @param m Matrix that contains all m mean vectors
#' @param m_ph vector that acts as a placeholder for new m vector
#' @param tilde_M Matrix that contains the tilde_M_i variance matrix
#' @param tilde_m Vector that contains the tilde_M_i mean vector
#' @param f_obs Field of vectors containing f at observed time points
#' @param f_star Field of vectors containing f at unobserved time points
#' @param pi Vector containing the sampled pi for this iteration
#' @param iter Iteration of MCMC step
#' @param S_obs Field of Matrices containing basis functions evaluated at observed time points
#' @param phi Cube of current phi paramaters
#' @param Z Cube that contains all past, current, and future MCMC draws
#' @export
updateZ_i <- function(M, M_ph, m, m_ph, tilde_M, tilde_m, f_obs, f_star, pi, iter, S_obs, phi, nu, Z) {
    invisible(.Call('_BayesFOC_updateZ_i', PACKAGE = 'BayesFOC', M, M_ph, m, m_ph, tilde_M, tilde_m, f_obs, f_star, pi, iter, S_obs, phi, nu, Z))
}

